version: 2

jobs:
  build:
    docker:
      # specific environment version to avoid incompatible updates
      - image: circleci/android:api-26-alpha

    environment:
      TERM: dumb
      JVM_OPTS: -Xmx3200m
      BUILD_PATH: $HOME/$CIRCLE_PROJECT_REPONAME/app/build
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError"'
      _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
      CI_BUILD_NUMBER: $CIRCLE_BUILD_NUM
      CI_BUILD_URL: $CIRCLE_BUILD_URL
      CI_BRANCH: $CIRCLE_BRANCH
      CI_COMMITTER_NAME: $CIRCLE_USERNAME

    steps:
      - checkout
      - run: chmod +x gradlew
      
      # fix error occurs when a file is missing as mentioned in https://circleci.com/docs/1.0/missing-file/
      - run: cp local.properties.ci local.properties

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      # try as mentioned in discuss.circleci.com/t/git-commit-message-in-environment-variable/533/3
      - run: export GIT_COMMIT_DESC="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"
      - run: echo $GIT_COMMIT_DESC
      - run: export CI_MESSAGE="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"
      
      - run: 
          name: Run test and collect coverage
          command: ./gradlew jacocoTestReport -PdisablePreDex
          no_output_timeout: 50m

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
          
      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results

      - run: mv app/build/reports/jacoco/jacocoTestReport app/build/reports/jacoco/test
      - run: ./gradlew coveralls
